---
- hosts: all
  vars:
    ruby: 2.1.5

  tasks:
    - name: make sure the system encoding is utf-8
      sudo: yes
      template: src=templates/locale dest=/etc/default/locale
                owner=root group=root mode=644

    - include: tasks/apt.yml
    - include: tasks/ruby.yml
    - include: tasks/shell_setup.yml

    - name: install bundler
      sudo_user: vagrant
      command: bash -lc "gem install bundler"

    - name: bundle install
      shell: 'executable=/bin/bash chdir=/vagrant . "$HOME/.rvm/scripts/rvm" && rvm use --default {{ ruby }} && bundle'
