---
- name: install key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: install rvm
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

- name: install ruby
  shell: ~/.rvm/bin/rvm install --default {{ ruby }} creates=~/.rvm/rubies/{{ ruby }}
